//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Selected Item.
        /// </summary>
        internal static string ApplySelectedItem {
            get {
                return ResourceManager.GetString("ApplySelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back To Base.
        /// </summary>
        internal static string BackToBase {
            get {
                return ResourceManager.GetString("BackToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy This Item.
        /// </summary>
        internal static string BuyThisItem {
            get {
                return ResourceManager.GetString("BuyThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Selected Ship.
        /// </summary>
        internal static string ChooseSelectedShip {
            get {
                return ResourceManager.GetString("ChooseSelectedShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose A Ship.
        /// </summary>
        internal static string ChooseShip {
            get {
                return ResourceManager.GetString("ChooseShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make this ship the default.
        /// </summary>
        internal static string ChooseShipDefault {
            get {
                return ResourceManager.GetString("ChooseShipDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the level. Press enter to return to the base..
        /// </summary>
        internal static string CompletedLevel {
            get {
                return ResourceManager.GetString("CompletedLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Server.
        /// </summary>
        internal static string ConnectToServer {
            get {
                return ResourceManager.GetString("ConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        internal static string CostLabel {
            get {
                return ResourceManager.GetString("CostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Colosseum.
        /// </summary>
        internal static string CreateColosseum {
            get {
                return ResourceManager.GetString("CreateColosseum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Gamble Match.
        /// </summary>
        internal static string CreateGambleMatch {
            get {
                return ResourceManager.GetString("CreateGambleMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Listen Server.
        /// </summary>
        internal static string CreateListenServer {
            get {
                return ResourceManager.GetString("CreateListenServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Player Ship.
        /// </summary>
        internal static string CreateNewPlayerShip {
            get {
                return ResourceManager.GetString("CreateNewPlayerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Buy Mode.
        /// </summary>
        internal static string CurrentBuyMode {
            get {
                return ResourceManager.GetString("CurrentBuyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current View Mode.
        /// </summary>
        internal static string CurrentViewMode {
            get {
                return ResourceManager.GetString("CurrentViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ship was destroyed. It has been rebuilt.
        /// </summary>
        internal static string DestroyShip {
            get {
                return ResourceManager.GetString("DestroyShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipped Item.
        /// </summary>
        internal static string EquippedItem {
            get {
                return ResourceManager.GetString("EquippedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit To Main Menu.
        /// </summary>
        internal static string ExitToMainMenu {
            get {
                return ResourceManager.GetString("ExitToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly To Planet.
        /// </summary>
        internal static string FlyToPlanet {
            get {
                return ResourceManager.GetString("FlyToPlanet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Base.
        /// </summary>
        internal static string GoToBase {
            get {
                return ResourceManager.GetString("GoToBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a ship before going to your base.
        /// </summary>
        internal static string GoToBaseDenied {
            get {
                return ResourceManager.GetString("GoToBaseDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Local Listen Server.
        /// </summary>
        internal static string HostLocalListenServer {
            get {
                return ResourceManager.GetString("HostLocalListenServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        internal static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Server.
        /// </summary>
        internal static string JoinServer {
            get {
                return ResourceManager.GetString("JoinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Players.
        /// </summary>
        internal static string MaxPlayers {
            get {
                return ResourceManager.GetString("MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Player.
        /// </summary>
        internal static string MultiPlayer {
            get {
                return ResourceManager.GetString("MultiPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Player Ship.
        /// </summary>
        internal static string NewPlayerShip {
            get {
                return ResourceManager.GetString("NewPlayerShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Item.
        /// </summary>
        internal static string NextItem {
            get {
                return ResourceManager.GetString("NextItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Ships.
        /// </summary>
        internal static string NumShips {
            get {
                return ResourceManager.GetString("NumShips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Credits:.
        /// </summary>
        internal static string PlayerCreditLabel {
            get {
                return ResourceManager.GetString("PlayerCreditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter to continue.
        /// </summary>
        internal static string PressToContinue {
            get {
                return ResourceManager.GetString("PressToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Item.
        /// </summary>
        internal static string PreviousItem {
            get {
                return ResourceManager.GetString("PreviousItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Main Menu.
        /// </summary>
        internal static string ReturnMainMenu {
            get {
                return ResourceManager.GetString("ReturnMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Game.
        /// </summary>
        internal static string ReturnToGame {
            get {
                return ResourceManager.GetString("ReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Ship And Play Game.
        /// </summary>
        internal static string SelectShipAndPlayGame {
            get {
                return ResourceManager.GetString("SelectShipAndPlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        internal static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Cost.
        /// </summary>
        internal static string ShipCost {
            get {
                return ResourceManager.GetString("ShipCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Name.
        /// </summary>
        internal static string ShipName {
            get {
                return ResourceManager.GetString("ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stat Name.
        /// </summary>
        internal static string StatName {
            get {
                return ResourceManager.GetString("StatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Port.
        /// </summary>
        internal static string TCPPort {
            get {
                return ResourceManager.GetString("TCPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Item.
        /// </summary>
        internal static string ThisItem {
            get {
                return ResourceManager.GetString("ThisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Port.
        /// </summary>
        internal static string UDPPort {
            get {
                return ResourceManager.GetString("UDPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit The Hangar.
        /// </summary>
        internal static string VisitHangar {
            get {
                return ResourceManager.GetString("VisitHangar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit The Shop.
        /// </summary>
        internal static string VisitShop {
            get {
                return ResourceManager.GetString("VisitShop", resourceCulture);
            }
        }
    }
}
